<?php

namespace ClientBundle\Repository;

/**
 * AuthAccessTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthAccessTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
