<?php

namespace ClientBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{


    public function findByPublication ($idpublication) {

    $query = $this->createQueryBuilder('c');
    $query = $query
        ->select('c.commentaire,c.datecom,c.id')
->addSelect('cl.path as path')
        ->addSelect('p.id as idPublication')
        ->innerJoin('c.publication','p')
         ->innerJoin('c.client','cl')
        ->where('p.id = :idpublication')
        ->setParameter('idpublication', $idpublication) ;

    return $query->getQuery()->getResult() ;

}
}
